// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWNNgl-OQZLeenIHPNe73k9Ez57iaaVN0',
    appId: '1:936344085208:web:4e97936d06e0047e922dad',
    messagingSenderId: '936344085208',
    projectId: 'lyfer-40955',
    authDomain: 'lyfer-40955.firebaseapp.com',
    storageBucket: 'lyfer-40955.firebasestorage.app',
    measurementId: 'G-4160BJRG3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZpS0yO0bQ28RbdQIkTST2y2p9_hc0GcU',
    appId: '1:936344085208:android:d500ef51ef495ced922dad',
    messagingSenderId: '936344085208',
    projectId: 'lyfer-40955',
    storageBucket: 'lyfer-40955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNXDlhgAeL6DBSW0yJujuEFylneQ41VH0',
    appId: '1:936344085208:ios:39879c13de9ee509922dad',
    messagingSenderId: '936344085208',
    projectId: 'lyfer-40955',
    storageBucket: 'lyfer-40955.firebasestorage.app',
    iosBundleId: 'com.example.lyfer',
  );
}
